Component Config Version: 12
Classes:
- objectId: 44e88fd0-a833-3ee6-0000-000000000000
  objectName: GetModbusTCP
  className: xg.nack.CTestClass
  Properties:
    Config File: C:/minifi-cpp/modbus.json
    Time Window Ms: 1000
    Freq: 100  
- objectId: 66e99f30-a866-3aa6-0000-000000000000
  objectName: SetModbusTCP
  className: xg.nanjing.CTestObj
  Properties:
    Config File: C:/minifi-cpp/test.json
    Time Window Ms: 200
    Freq: 200      
Connects:
- connectId: 77e44f30-a811-3aa6-0000-000000000123
  connectName: GetModbusTCP/SetModbusTCP
  objectSrcId: 44e88fd0-a833-3ee6-0000-000000000000
  objectDestId: 66e99f30-a866-3aa6-0000-000000000000
